# Generated by Django 4.2.6 on 2023-11-14 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostBoard_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='res_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='PostBoard_main.posts'),
        ),
        migrations.AlterField(
            model_name='response',
            name='res_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(),
        ),
    ]
